// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: stops.sql

package database

import (
	"context"
)

const clearAllStops = `-- name: ClearAllStops :exec
DELETE FROM stops
`

func (q *Queries) ClearAllStops(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, clearAllStops)
	return err
}

const createStop = `-- name: CreateStop :exec
INSERT INTO stops (
  id, name
) VALUES (
  ?, ?
)
`

type CreateStopParams struct {
	ID   string
	Name string
}

func (q *Queries) CreateStop(ctx context.Context, arg CreateStopParams) error {
	_, err := q.db.ExecContext(ctx, createStop, arg.ID, arg.Name)
	return err
}
